blank_lines_upper_bound = 2
combine_control_expr = false
edition = "2021"
force_multiline_blocks = true
format_code_in_doc_comments = true
format_generated_files = false
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
max_width = 120