array_width = 50
blank_lines_upper_bound = 2
chain_width = 40
combine_control_expr = false
edition = "2021"
fn_single_line = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_generated_files = false
format_strings = true
imports_layout = "HorizontalVertical"
indent_style = "Visual"
match_arm_leading_pipes = "Always"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
struct_lit_single_line = false
use_field_init_shorthand = true